---

- name: Packages
  become: true
  apt:
    pkg:
    - python3
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg 
    - lsb-release
    state: latest
    update_cache: true


- name: Docker APT Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable"
    state: present


- name: Docker Engine
  become: true
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true


- name: Add User
  become: true
  user:
    name: "{{ item.username }}"
    groups: docker
    append: yes
  with_items: "{{ users }}"