all:
  hosts:
    nginx:
  children:
    managers:
      hosts:
        manager-main:
    workers:
      hosts:
        worker-one:
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'