all:
  hosts:
    nginx:
  children:
    managers:
      hosts:
        manager:
    workers:
      hosts:
        worker-a:
  vars:
    ansible_user: pc
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    docker_users:
      - username: jenkins